---
title: "Markov Models"
author: "Chris Bentz"
date: "22/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages
If the libraries are not installed yet, you need to install them using, for example, the command: install.packages("ggplot2"). For the Hrate package this is different, since it comes from github. The devtools library needs to be installed, and then the install_github() function is used.

```{r, message = F}
library(markovchain)
library(stringr)
```

```{r}
# choose file with sequenceThe document you are reading is not a static web page, but an interactive environment called a Colab notebook that lets you write and execute code.

For example, here is a code cell with a short Python script that computes a value, stores it in a variable, and prints the result:
file <- "~/Github/StringBase/corpus/original/paleolithic/paleolithic_vhc_0145.txt"
#file <- "~/Github/StringBase/corpus/original/paleolithic/paleolithic_sgr_0001.txt"
#file <-  "~/Github/StringBase/corpus/generated/test/original/test_english_1stArticle.txt"

# read sequence into R
textfile <- scan(file, what = "char", quote = "", comment.char = "", 
                   encoding = "UTF-8", sep = "\n" , skip = 7) 

# preprocessing
# remove annotations marked by '<>'
textfile <- gsub("<.*>","",textfile) 
textfile <- str_replace_all(textfile, c("\\\t" = "", "\\(" = "", "\\)" = "", 
                                       "\\]" = "", "\\[" = "",  "\\}" = "",  "\\{" = ""))
char.sequence <- unlist(strsplit(textfile, ""))
char.sequence <- c("G","i","t","t","i"," ","G","i","t","t","i"," ")
```

# Markov chain
```{r}
markov.fitted <- markovchainFit(char.sequence)
print(markov.fitted)
```